<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><?=\Ia\Config::get('title');?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap-theme.min.css" rel="stylesheet">

    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link type="text/css" href="/css/smoothness/jquery-ui-1.8.18.custom.css" rel="stylesheet" />
    <link href="/css/style.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?libraries=drawing&key=<?=\Ia\Config::get('googleMapsApiKey');?>&sensor=false">
    </script>

    <? echo $this->headStyle(); ?>
    <? echo $this->headLink(); ?>

  </head>

  <body>

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><?=\Ia\Config::get('title');?></a>
            </div>
            <div class="collapse navbar-collapse">
                <?php echo $this->placeholder('nav') ?>
                <?php
                if(!Zend_Registry::isRegistered('auth')):
                ?>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/user/register">Register</a></li>
                    <li><a href="/user/login">Login</a></li>
                </ul>
                <?php
                else:
                $user = Zend_Registry::get('auth');
                ?>
                <ul class="nav navbar-nav navbar-right">
                <li>
                        <a href="/message/">
                        <?php if(count($user->inbox)>0): ?>
                        <span class="badge badge-info"><?=count($user->inbox)?></span>
                        <?php else: ?>
                        <span class="badge">0</span>
                        <?php endif; ?>
                        </a>
                </li>
                <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-white glyphicon-cog"></i><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                                <?php
                                if(Zend_Registry::isRegistered('acl')):
                                    $acl = Zend_Registry::get('acl');
                                    if($acl->isAllowed($user->role,'settings_clear-cache')):
                                    ?>
                                    <li><a href="/settings/clear-cache">Clear Cache</a></li>
                                    <?php
                                    endif;
                                    if($acl->isAllowed($user->role,'log_index')):
                                    ?>
                                    <li><a href="/log/index">View Log</a></li>
                                    <?php
                                    endif;
                                    if($acl->isAllowed($user->role,'user_password-reset')):
                                    ?>
                                    <li><a href="/user/password-reset">Reset Password</a></li>
                                    <?php
                                    endif;
                                    if($acl->isAllowed($user->role,'support_index')):
                                    ?>
                                    <li><a href="/support">Contact Support</a></li>
                                    <?php
                                    endif;
                                endif;
                                ?>
                        </ul>
                </li>
                <li><a onclick="return confirm('Are you sure you want to log out?');" href="/user/logout"><i class="glyphicon glyphicon-white glyphicon-off"></i></a></li>
                </ul>
                <p class="navbar-text navbar-right"><?=$user->first_name?> <?=$user->last_name?> (<?=$user->role?>)</p>
                <?php endif; ?>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <div class="container">

        <div class="alerts">
        <?=Ia_View_Helper_Alert::showAlerts();?>
        </div>

        <?php
        $sidebar = $this->placeholder('sidebar')->toString();
        if($sidebar):
        ?>
            <div class="row">
                <div class="col-sm-3 sidebar">
                    <?=$sidebar;?>
                    <!--<ul class="nav nav-sidebar">
                    <li class="active"><a href="#">Overview</a></li>
                    <li><a href="#">Reports</a></li>
                    <li><a href="#">Analytics</a></li>
                    <li><a href="#">Export</a></li>
                    </ul>-->
                </div>
                <div class="col-sm-9 main">
                    <?=$this->layout()->content ?>
                </div>
            </div>
        <?php
        else:
        ?>
            <?=$this->layout()->content ?>
        <?php
        endif;
        ?>

        <!-- Backbone Templates -->

        <script type="text/template" id="ia-alerts">
        <% if(type=='error') { type = 'danger'; } %>
        <div class="alert alert-block alert-<%= type %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <% if(typeof heading !== 'undefined' && heading!==null) { %>
        <h4 class="alert-heading"><%= heading %></h4>
        <% } %>
        <%= message %>
        </div>
        </script>

        <script type="text/template" id="single-select-widget">
            <div class="control-group">
                <label class="control-label"><%= this.model.label %></label>
                <div class="controls">
                  <select name="<%= this.model.name %>">
                    <option><%= this.model.nullLabel %></option>
                    <% _.each(this.model.models, function(item) { %> <option value="<%= item.attributes[item.primaryKey] %>"><%= item.attributes[item.stringIdentifier] %></option> <% }); %>
                  </select>
                </div>
            </div>
        </script>

        <script type="text/template" id="ia-grid-perpage">
        <form method="post" action=""><label for="perPage">Per Page</label>
        <select name="perPage" id="perPage">
        <option value="10"<% if(itemCountPerPage==10){%> selected="selected"<% } %>>10</option>
        <option value="25"<% if(itemCountPerPage==25){%> selected="selected"<% } %>>25</option>
        <option value="50"<% if(itemCountPerPage==50){%> selected="selected"<% } %>>50</option>
        <option value="100"<% if(itemCountPerPage==100){%> selected="selected"<% } %>>100</option>
        </select></form>
        </script>

        <script type="text/template" id="ia-grid-page">
        <div class="pagination paginationControl pagination-left">
        <ul>
        <% for(i=1;i<=pageCount;i++) { %>
            <% var thisClass=''; %>
            <% if(i==current) thisClass += 'active '; %>
            <% if(i==last) thisClass += 'last '; %>
            <% if(thisClass!=='') { %>
                <li class="<%=thisClass%>"><a href="#"><%= i %></a></li>
            <% } else { %>
                <li><a href="#"><%= i %></a></li>
            <% } %>
        <% } %>
        </ul>
        </div>
        </script>

        <!-- Backbone Templates -->


  </div> <!-- /container -->

      <!-- Terms/Conditions -->
<div class="modal fade" id="termsConditions">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Terms &amp; Conditions</h4>
      </div>
      <div class="modal-body">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="/js/jquery-3.1.1.js"></script>-->
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.cookie.js"></script>
    <script src="/js/jquery-ui-1.8.18.custom.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/json2.js"></script>
    <script src="/js/underscore-1.3.1.js"></script>
    <script src="/js/backbone-min.js"></script>
    <script src="/js/accordionize.js"></script>
    <script src="/js/ia.js"></script>
    <script src="/js/main.js"></script>
    <? echo $this->headScript(); ?>
    <?php if(APPLICATION_ENV!='production'): ?>
        <center><div class="env"><?=gethostname()?> : <?=APPLICATION_ENV?></div></center>
    <?php endif; ?>
  </body>
</html>
